# Generated by Django 6.0.6 on 2026-06-29 18:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefFiliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('idcours', models.AutoField(primary_key=True, serialize=False)),
                ('codcours', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('idfonction', models.AutoField(primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('idrole', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('idsemestre', models.AutoField(primary_key=True, serialize=False)),
                ('libsemestre', models.CharField(max_length=50)),
                ('datedeb', models.DateField()),
                ('datefin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeEvaluation',
            fields=[
                ('idtype', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('descript', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('idevaluation', models.AutoField(primary_key=True, serialize=False)),
                ('lib', models.CharField(max_length=100)),
                ('coefficient', models.IntegerField(default=1)),
                ('duree', models.DurationField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cours')),
                ('type_eval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typeevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('idfiliere', models.AutoField(primary_key=True, serialize=False)),
                ('codfiliere', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=100)),
                ('descript', models.TextField(blank=True, null=True)),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filieres_dirigees', to='app.cheffiliere')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='app.filiere'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('idprom', models.AutoField(primary_key=True, serialize=False)),
                ('libnom', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('niveau', models.CharField(max_length=50)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.filiere')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.semestre'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('postnom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminim')], max_length=1, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('mat', models.CharField(blank=True, max_length=50, null=True)),
                ('tel_2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='profile_pics/')),
                ('is_validated', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='app_user_set', related_query_name='app_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='app_user_set', related_query_name='app_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('idpersonnel', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=100)),
                ('fonction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.fonction')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_inscription', models.DateField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='cheffiliere',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.CreateModel(
            name='Cotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotations', to='app.etudiant')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotations', to='app.evaluation')),
            ],
            options={
                'unique_together': {('etudiant', 'evaluation')},
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('idinscription', models.AutoField(primary_key=True, serialize=False)),
                ('annee', models.IntegerField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='app.etudiant')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='app.promotion')),
            ],
            options={
                'unique_together': {('etudiant', 'promotion')},
            },
        ),
        migrations.CreateModel(
            name='UtilisateurRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur_roles', to='app.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur_roles', to='app.user')),
            ],
            options={
                'unique_together': {('user', 'role')},
            },
        ),
    ]
